@PokerApi_HostAddress = http://localhost:5073

### Health Check
GET {{PokerApi_HostAddress}}/health
Accept: application/json

###

### Get All Tables
GET {{PokerApi_HostAddress}}/tables
Accept: application/json

###
